apiVersion: v1
kind: PersistentVolume
metadata:
  name: coturn-pv1
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: coturn-claim1
    namespace: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mod/coturn/entrypoint.sh"
