apiVersion: v1
kind: PersistentVolume
metadata:
  name: freeswitch-pv0
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: freeswitch-claim0
    namespace: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mod/freeswitch/conf/sip_profiles"
