apiVersion: v1
kind: PersistentVolume
metadata:
  name: bbb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /persistentVolume
    server: 10.21.145.2