apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001" 
spec:
  capacity:
    storage: "5Gi" 
  accessModes:
    - ReadOnlyOnce
  gcePersistentDisk: 
    fsType: "ext4" 
    pdName: "bbb-gke-pv" 