apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bigbluebutton-claim
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
status: {}
