apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssl-data
spec:
  volumeName: ssl-data-pv
  storageClassName: "ssl-data"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
