apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-freeswitch
spec:
  volumeName: vol-freeswitch-pv
  storageClassName: "vol-freeswitch"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
