apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: coturn
  name: coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coturn
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: coturn
        app: coturn
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - args:
            - --external-ip=34.80.142.158/34.80.142.158
            - --external-ip=::1/::1
            - --static-auth-secret=86b5SM4DJdbODf54AL6feE7bBIG7R5WD
          env:
            - name: ENABLE_HTTPS_PROXY
              value: "false"
            - name: COTURN_TLS_CERT_PATH
              value: /tmp/cert.pem
            - name: COTURN_TLS_KEY_PATH
              value: /tmp/key.pem
          image: asia-east1-docker.pkg.dev/mplus-video-conference-dev/mplus/coturn:4.5-alpine
          ports:
          - containerPort: 5349
          name: coturn
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /tmp
              name: coturn-config-volume
            - mountPath: /etc/
              name: coturn-server-conf-volume
      restartPolicy: Always
      volumes:
        - name: coturn-config-volume
          configMap:
            name: coturn-config
        - name: coturn-server-conf-volume
          configMap:
            name: coturn-server-conf
status: {}
