apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
        app: external
    spec:
      # hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: asia-east1-docker.pkg.dev/mplus-video-conference-dev/mplus/bbb-k8s-nginx:v2.5.5-3
          name: nginx
          ports:
          - name: https
            containerPort: 443

          resources: {}
          volumeMounts:
            - mountPath: /var/bigbluebutton
              name: bigbluebutton
            - mountPath: /html5-static
              name: html5-static
              readOnly: true
            - mountPath: /etc/nginx/bbb/
              name: nginx-config-volume

            - mountPath: /etc/nginx/conf.d/
              name: nginx-default-config-volume

            - mountPath: /tmp/
              name: ssl-config-volume
              # need to think how to pass into it
            - mountPath: /www/default.pdf
              name: nginx-default-pdf-volume
              subPath: "default.pdf"
      restartPolicy: Always
      volumes:
        - name: bigbluebutton
          persistentVolumeClaim:
            claimName: bigbluebutton
            
        - name: html5-static
          persistentVolumeClaim:
            claimName: html5-static
            readOnly: true

        - name: nginx-config-volume
          configMap:
            name: nginx-config

        - name: nginx-default-config-volume
          configMap:
            name: nginx-default-config

        - name: ssl-config-volume
          configMap:
            name: ssl-config

        - name: nginx-default-pdf-volume
          configMap:
            name: nginx-default-pdf
status: {}
