apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: loadbalancer
    app: loadbalancer
  name: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: "48087"
      port: 50100
      targetPort: 50100
  selector:
    io.kompose.service: nginx-service
  loadBalancerIP: 34.81.117.231
status:
  loadBalancer: {}
