apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
## guess the following code mount the G:\code\k8s\conf dir to container /etc/mongo conf
        volumeMounts:
          - name: mongodb-dir  
            mountPath: /etc/mongo/
          - name: mongodb-conf   
            mountPath: /etc/mongo/mongod.conf
      volumes:
        - name: mongodb-dir
          hostPath:
            path: /home/m11007312_gcp/bigbluebutton-docker/mod/mongo/
            type: DirectoryOrCreate
        - name: mongodb-conf
          hostPath:
            path: /home/m11007312_gcp/bigbluebutton-docker/mod/mongo/mongod.conf
            type: File