apiVersion: v1
kind: PersistentVolume
metadata:
  name: bigbluebotton-pv
spec:
  storageClassName: bigbluebotton
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: gcs-fuse-demo-bucket
    # readOnly: true #optional
  # nfs:
  #   path: /persistentVolume
  #   server: 10.21.145.2