apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssl-data-pv
spec:
  storageClassName: ssl-data
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /persistentVolume
    server: 10.21.145.2