apiVersion: v1
kind: Service
metadata:
  name: freeswitch-service
spec:
  type: ClusterIP
  ports:
  - name: fsesl
    port: 7443
    protocol: TCP
    targetPort: 7443
  selector:
    app: freeswitch
  clusterIP: 5.1.0.50
