apiVersion: v1
kind: Service
metadata:
  name: freeswitch-service
spec:
  type: ClusterIP
  ports:
  - name: nginx
    port: 7444
    protocol: TCP
    targetPort: 7444

  - name: fsesl
    port: 8021
    protocol: TCP
    targetPort: 8021

  - name: webrtc-sfu
    port: 5066
    protocol: TCP
    targetPort: 5066
  
  - name: sips
    port: 5081
    protocol: TCP
    targetPort: 5081  

  selector:
    io.kompose.service: freeswitch
  clusterIP: 5.1.0.50
