apiVersion: v1
kind: Service
metadata:
  name: freeswitch-service
spec:
  type: ClusterIP
  ports:
  - name: nginx
    port: 7443
    protocol: TCP
    targetPort: 7443

  - name: fsesl
    port: 8021
    protocol: TCP
    targetPort: 8021

  - name: webrtc-sfu
    port: 5066
    protocol: TCP
    targetPort: 5066
  
  # {{range $i := loop 0 10}}
  - port: {{ add 16384 1}}
    protocol: UDP
    targetPort: {{ add 16384 1}}
    name: UDP-{{ add 16384 1}}
  # {{end}}

  selector:
    app: freeswitch
  clusterIP: 5.1.0.50
