apiVersion: v1
kind: Service
metadata:
  name: html5-backend-1-service
spec:
  type: ClusterIP
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: html5-backend-1
  clusterIP: 5.1.0.11
