apiVersion: v1
kind: Service
metadata:
  name: html5-frontend-1-service
spec:
  type: ClusterIP
  ports:
  - port: 4100
    protocol: TCP
    targetPort: 4100
  selector:
    app: html5-frontend-1
  clusterIP: 5.1.0.12
