apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-service-lbc
    app: nginx-service-lbc
  name: nginx-service-lbc
  
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: https

  selector:
    app: nginx
  loadBalancerIP: 34.81.117.231
  
status:
  loadBalancer: {}