apiVersion: v1
kind: Service
metadata:
  name: webhooks-service
spec:
  type: ClusterIP
  ports:
  - name: nginx
    port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: webhooks
  clusterIP: 5.1.0.17