apiVersion: v1
kind: Service
metadata:
  name: webrtc-sfu-service
spec:
  type: ClusterIP
  ports:
  # - name: nginx
  - port: 3008
    protocol: TCP
    targetPort: 3008
  selector:
    app: webrtc-sfu
  clusterIP: 5.1.0.40
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-service
# spec:
#   type: ClusterIP
#   ports:
#   - port: 6379
#     protocol: TCP
#     targetPort: 6379
#   selector:
#     app: redis
#   clusterIP: 5.1.0.5
