apiVersion: v1
kind: PersistentVolume
metadata:
  name: https-proxy-pv1
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: https-proxy-claim1
    namespace: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mod/https/site-ipv4only.conf"
