apiVersion: v1
kind: Service
metadata:
  name: bbb-web-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: bbb-web
  clusterIP: 10.111.83.2
