apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bigbluebutton
  name: bigbluebutton-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: bigbluebutton
  resources:
    requests:
      storage: 100Mi
status: {}
