apiVersion: v1
kind: PersistentVolume
metadata:
  name: cert-pv1
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: cert-claim1
    namespace: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tmp/cert.pem"
