apiVersion: v1
kind: Service
metadata:
  name: etherpad-service
spec:
  type: ClusterIP
  ports:
  - port: 6380
    protocol: TCP
    targetPort: 6380
  selector:
    app: etherpad
  clusterIP: 10.111.83.4
