apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv0
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: mongodb-claim0
    namespace: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mod/mongo/mongod.conf"
