apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ssl-data
  name: ssl-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
