apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vol-freeswitch
  name: vol-freeswitch
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
