apiVersion: v1
kind: Service
metadata:
  name: webhooks-service
spec:
  type: ClusterIP
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: webhooks
  clusterIP: 10.111.83.17
